env:
  es6: true
extends:
  - google
  - plugin:prettier/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2018
  project: './tsconfig.json'
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  require-jsdoc:
    - off
  quotes:
    - warn
    - single
  no-unused-vars:
    - off
  '@typescript-eslint/no-unused-vars':
    - error
