env:
  es6: true
extends:
  - google
  - 'plugin:@typescript-eslint/recommended'
  - plugin:prettier/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2018
  project: './tsconfig.json'
  sourceType: module
plugins:
  - react
  - babel
  - '@typescript-eslint'
rules:
  require-jsdoc:
    - off
  quotes:
    - warn
    - single
  no-invalid-this:
    - off
  babel/no-invalid-this:
    - error
  '@typescript-eslint/indent':
    - error
    - 2
  '@typescript-eslint/no-parameter-properties':
    - off
