env:
  browser: true
extends:
  - ../.eslintrc.yml
  - plugin:react/recommended
parserOptions:
  ecmaFeatures:
    jsx: true
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
rules:
  react/jsx-uses-vars:
    - error
  react/jsx-no-bind:
    - error
settings:
  react:
    version: detect
